# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sales_records.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13sales_records.proto\"\x0e\n\x0c\x45mptyMessage\"&\n\x17PingSalesRecordResponse\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2I\n\x0bSalesRecord\x12:\n\x0fPingSalesRecord\x12\r.EmptyMessage\x1a\x18.PingSalesRecordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_records_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTYMESSAGE']._serialized_start=23
  _globals['_EMPTYMESSAGE']._serialized_end=37
  _globals['_PINGSALESRECORDRESPONSE']._serialized_start=39
  _globals['_PINGSALESRECORDRESPONSE']._serialized_end=77
  _globals['_SALESRECORD']._serialized_start=79
  _globals['_SALESRECORD']._serialized_end=152
# @@protoc_insertion_point(module_scope)
