services:
  srv_persistor:
    build: 
      context: ./
      dockerfile: ./srv_persistor/Dockerfile
    ports:
      - "50051:50051"
  srv_reader:
    build: 
      context: ./
      dockerfile: ./srv_persistor/Dockerfile
    depends_on:
      - srv_persistor